name: 'Chromatic'
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot-preview[bot]'
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
