name: 'Chromatic'
on:
  pull_request:
    types:
      - closed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot-preview[bot]' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
