name: CI

on: push

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.19

      - name: Install dependencies
        run: yarn
      - name: Run Prettier
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.19

      - name: Install dependencies
        run: yarn
      - name: Run ESLint
        run: yarn lint:check

  types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.19

      - name: Install dependencies
        run: yarn
      - name: Run Typescript
        run: yarn types:check

  test:unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.19

      - name: Install dependencies
        run: yarn
      - name: Run Jest
        run: yarn test

  test:e2e:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.19

      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: yarn playwright install chromium --with-deps
      - name: Run Playwright tests
        env:
          NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_LEGACY_APP_URL: ${{ secrets.NEXT_PUBLIC_LEGACY_APP_URL }}
          NEXT_PUBLIC_AUTH_URL: ${{ secrets.NEXT_PUBLIC_AUTH_URL }}
          NEXT_PUBLIC_SOCKET_URL: ${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
          NEXT_PUBLIC_NEW_ANNOUNCEMENTS_URL: ${{ secrets.NEXT_PUBLIC_NEW_ANNOUNCEMENTS_URL }}
          NEXT_PUBLIC_NEWSLETTER_API_URL: ${{ secrets.NEXT_PUBLIC_NEWSLETTER_API_URL }}
          NEXT_PUBLIC_NEWSLETTER_EMAIL_LIST_ID: ${{ secrets.NEXT_PUBLIC_NEWSLETTER_EMAIL_LIST_ID }}
          NEXT_PUBLIC_TAXONOMY_URL: ${{ secrets.NEXT_PUBLIC_TAXONOMY_URL }}
          NEXT_PUBLIC_CULTUURKUUR_LOCATION_ID: ${{ secrets.NEXT_PUBLIC_CULTUURKUUR_LOCATION_ID }}
          NEXT_PUBLIC_SHOULD_SHOW_BETA_VERSION: ${{ secrets.NEXT_PUBLIC_SHOULD_SHOW_BETA_VERSION }}
          E2E_TEST_EMAIL: ${{ secrets.E2E_TEST_EMAIL }}
          E2E_TEST_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}

        run: yarn playwright test
